language: go
os:
- linux
- osx
script:
- go build -o unrealsync-`uname | tr '[:upper:]' '[:lower:]'`
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IAeDvwnkag/EjgmNpsvJLa46YUeoAHghxUUodszTR+OJuC49RdIX2Y0FaeCSDs0DUoXnjy2mvpnEhfob6l5U/q2VdOhd+cXnUhCZylvJSxgKb58tkyJY2BLy5SbvNvymdehBoAm8hxV6Io9H2vHCm86qlgGuE6+IJqWyQq3keBF4mCCPW2zyTHCTHKhUMwe8mmrU3XpicwTvWAFaOVq2C/HylaOuqlkipMQz4Q5cf9XNHj29Pppm3xChy1m8evRooju71fo+eu+/hexERmhdWZcFe9z6Ji2aAHdNFPW9nPlGQIMwGs6bGAx1Gtwh0p9Onc7FxERAAOJSQVgYBa57QuZhlaVKfi46GSvWEM8PJ9AssiIVAB/8ISPgdcom90Zpn/5Wr1WxYTQ6T5JxJOi81bnmrKqCu8ix3wGvuBk9KMGA+gYhKuuxCo9XhmHto7IjUBuzNRhQ07CgrdGqQgKmG2Q4R6kpcKGbli3HYSGzkl8MrfABxIcfLjREQBfA1KX+zltdXSkrquOWaNhgsQTqLDagisnz8MtxT1RQEGZ8rY7N+Q5GmssfZ1DZIWjW70PDDmgp/377gs5rqGmHFnM1sjp3jLA4yoeTXHxNagKTJbUMPsdKqssqlFBfW4eiXQsh6z70PtDzu3e9NbSlqXlDr6hPAS0fF+yXCPXpXEWW9nc=
  file_glob: true
  file: unrealsync-*
  on:
    repo: unrealsync/unrealsync
    tags: true
